config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :categories, only:[:index, :new, :create, :show] do
    resources :products, only:[:index, :new, :create, :show]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products

  validates :name,
            presence: true,
            uniqueness: true,
            length: { minimum: 3 }
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :category

  validates :name,
            presence: true,
            uniqueness: true,
            length: { minimum: 3 }

  validates :price,
            presence: true,
            # format: { with: /\A\d+(?:\.\d{0,2})?\z/ },
            # format: { with: /^(\$)?(\d+)(\.|,)?\d{0,2}?$/ }
            # format: { with: /^\d{1,4}(\.\d{0,2})?$/ },
            numericality: {greater_than: 0}

  # validates_format_of :price { with: /\d{0,10}\.\d{2}/ }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # layout 'application'
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path
      flash[:notice] = "Success!"
    else
      render "categories/new"
    end
  end

  def show
    @category = Category.find(params[:id])
    @products = Product.where(category_id: @category)
  end

  private
  def category_params
    params.require(:category).
    permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def new
    @product = Product.new
    @category = Category.find(params[:category_id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
      flash[:notice] = "Success!"
    else
      render "products/new"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  private
  def product_params
    params.require(:product).
    permit(
      :name,
      :price,
      :description,
      :category_id
      )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @categories = Category.all
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<h3> Create a new category </h3>
<%= link_to "Home", root_path %>

<div id ="wrapper">
  <%= form_for @category do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.submit "Submit" %>
    </div>
  <% end %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h5> The following errors(s) occurred: </h5>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div id ="wrapper">

  <h1><%= @category.name %></h1><%= link_to "Home", root_path %>
  <ul>
    <% @products.each do |product| %>
      <li><%= product.name %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/products/new.html.erb
<div id ="wrapper">
  <h1>New</h1>
  <%= link_to "Home", root_path %>
    <%= form_for @product, url: category_products_path do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :price %>
        <%= f.text_field :price %>
      </div>
      <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
      </div>
        <%= f.hidden_field :category_id, value: params[:category_id] %>
        <%= f.submit "Submit"%>
      </div>
    <% end %>

  <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/welcome/index.html.erb
<h4>Categories <%= link_to "(Create)", new_category_path, id: "cat_create" %></h4>
<%= link_to "Home", root_path %>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div id ="wrapper">
  <ul id="categories">
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %>
        <%= link_to "(Create)", new_category_product_path(category), id: "prod_create" %>
    </li>
  <% end %>
  <h4>All products</h4>

  <div id="mainlist">
    <ul>
      <% @products.each do |product| %>
        <li>Category: <%= product.category.name %></li>
        <li>Name: <%= product.name %></li>
        <li>Price: $<%= product.price %></li>
        <li>Description: <%= product.description %></li>
        </br>
      <% end %>
    </ul>
  </div>
</div>